CREATE TABLE fac_estate_offers_snpt (
    pk_offer_id INT PRIMARY KEY IDENTITY(1,1),
    dd_offer_id INT,
    source_id TINYINT,
    snpt_date_id INT,
    create_date_id INT,
    modify_date_id INT,
    city_id TINYINT,
    market_type_id TINYINT,
    offer_characteristics_id TINYINT,
    title VARCHAR(MAX),
    url VARCHAR(MAX),
    price FLOAT,
    area FLOAT,
    price_per_square_m FLOAT,
    floor INT,
    rooms_number TINYINT,
    rent FLOAT,
    building_year INT,
    CONSTRAINT FK_offer_characteristics FOREIGN KEY (offer_characteristics_id) REFERENCES dim_offer_characteristics(pk_offer_characteristics_id),
    CONSTRAINT FK_snpt_date FOREIGN KEY (snpt_date_id) REFERENCES dim_date(pk_date_id),
    CONSTRAINT FK_source_id FOREIGN KEY (source_id) REFERENCES dim_source_type(pk_source_id),
    CONSTRAINT FK_city_id FOREIGN KEY (city_id) REFERENCES dim_city(pk_city_id),
    CONSTRAINT FK_market_type FOREIGN KEY (market_type_id) REFERENCES dim_market_type(pk_market_type_id)
);